# =============================================================================
# ConfigMap — Non-sensitive configuration
# =============================================================================
apiVersion: v1
kind: ConfigMap
metadata:
  name: statement-api-config
  namespace: statement-api
data:
  SERVER_PORT: "8093"
  SPRING_PROFILES_ACTIVE: "docker"
  SPRING_RABBITMQ_HOST: "rabbitmq-service"
  SPRING_RABBITMQ_PORT: "5672"
  AZURE_BLOB_STORAGE_URL: "http://azurite-service:10000/devstoreaccount1"
  DOWNLOAD_BASE_URL: "http://statement-api-service:8093/api/v1/statements/download"
  OAUTH2_ISSUER_URI: "https://login.microsoftonline.com/95d6a08d-8d38-495b-9c70-ab0cacd42d64/v2.0"
  OAUTH2_AUDIENCE: "eb596b75-d742-4786-8325-2a55591c69d9"
