-- Create STATEMENT table
CREATE TABLE IF NOT EXISTS STATEMENT (
    ID                  VARCHAR(36)     NOT NULL,
    CUSTOMER_ID         VARCHAR(50)     NOT NULL,
    STATEMENT_DATE      TIMESTAMP       NOT NULL,
    STATEMENT_TYPE      VARCHAR(20)     NOT NULL,
    ACCOUNT_NUMBER      VARCHAR(20)     NOT NULL,
    FILE_NAME           VARCHAR(255)    NOT NULL,
    FILE_SIZE           BIGINT,
    CONTENT_HASH        VARCHAR(64),
    BLOB_PATH           VARCHAR(500),
    STATUS              VARCHAR(20)     DEFAULT 'AVAILABLE',
    RETENTION_DAYS      INT             DEFAULT 365,
    VERSION             BIGINT          DEFAULT 0 NOT NULL,
    CREATED_AT          TIMESTAMP       DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT          TIMESTAMP       DEFAULT CURRENT_TIMESTAMP,
    CREATED_BY          VARCHAR(255),
    UPDATED_BY          VARCHAR(255),
    CONSTRAINT PK_STATEMENT PRIMARY KEY (ID)
);

-- Create DOWNLOAD_LINK table
CREATE TABLE IF NOT EXISTS DOWNLOAD_LINK (
    ID                  VARCHAR(36)     NOT NULL,
    STATEMENT_ID        VARCHAR(36)     NOT NULL,
    TOKEN               VARCHAR(500)    NOT NULL,
    EXPIRES_AT          TIMESTAMP       NOT NULL,
    MAX_DOWNLOADS       INT             DEFAULT 5,
    DOWNLOAD_COUNT      INT             DEFAULT 0,
    STATUS              VARCHAR(20)     DEFAULT 'ACTIVE',
    DOWNLOADED_AT       TIMESTAMP,
    DOWNLOADED_BY_IP    VARCHAR(45),
    VERSION             BIGINT          DEFAULT 0 NOT NULL,
    CREATED_AT          TIMESTAMP       DEFAULT CURRENT_TIMESTAMP,
    CREATED_BY          VARCHAR(255),
    CONSTRAINT PK_DOWNLOAD_LINK PRIMARY KEY (ID),
    CONSTRAINT FK_DL_STATEMENT FOREIGN KEY (STATEMENT_ID) REFERENCES STATEMENT(ID) ON DELETE CASCADE
);

-- Create indexes
CREATE INDEX IF NOT EXISTS IDX_STMT_CUSTOMER_ID ON STATEMENT(CUSTOMER_ID);
CREATE INDEX IF NOT EXISTS IDX_STMT_STATUS ON STATEMENT(STATUS);
CREATE INDEX IF NOT EXISTS IDX_STMT_DATE ON STATEMENT(STATEMENT_DATE);
CREATE INDEX IF NOT EXISTS IDX_DL_TOKEN ON DOWNLOAD_LINK(TOKEN);
CREATE INDEX IF NOT EXISTS IDX_DL_STATUS ON DOWNLOAD_LINK(STATUS);
CREATE INDEX IF NOT EXISTS IDX_DL_EXPIRES_AT ON DOWNLOAD_LINK(EXPIRES_AT);
